#pragma once

#include <memory>
#include <span>

#include "firefly/core/tensor.h"
#include "firefly/device/context.h"

namespace firefly::model
{

/** @brief Inputs required by a model-agnostic speculative token proposer. */
struct SpeculativeProposalInput
{
    int           anchor_token = -1;         ///< Last committed target token that anchors the proposal block.
    int           token_count = 0;           ///< Maximum number of tokens requested from the proposer.
    const Tensor* target_context = nullptr;  ///< Optional compact target hidden-state context; borrowed for this call.
    device::Context context;                 ///< CUDA stream and allocation context for proposal execution.
};

/** @brief Device-resident token block and optional confidence scores returned by a proposer. */
struct SpeculativeProposal
{
    Tensor token_ids;   ///< Proposed token IDs, shaped `[token_count]` with `DType::I32`.
    Tensor confidence;  ///< Optional per-position acceptance confidence in proposer dtype.
};

/** @brief Target-model dimensions exposed to proposer compatibility validation. */
struct SpeculativeTargetMetadata
{
    int hidden_size = 0;        ///< Width of target hidden states supplied to the proposer.
    int vocab_size = 0;         ///< Target tokenizer and language-head vocabulary size.
    int num_hidden_layers = 0;  ///< Number of addressable target hidden layers.
};

/**
 * @brief Optional model capability that produces speculative token blocks.
 *
 * Implementations own draft-model details such as mask tokens, context projection,
 * block topology, and confidence heads. The execution engine depends only on this
 * capability, allowing different proposer architectures to share verification logic.
 */
class SpeculativeProposer
{
public:
    /** @brief Enables destruction through the capability interface. */
    virtual ~SpeculativeProposer() = default;

    /**
     * @brief Allocates proposer-specific runtime state for the requested sequence capacity.
     * @param max_sequence_slots Maximum number of scheduler slots that may be active concurrently.
     * @param context Device and CUDA stream used for asynchronous initialization.
     * @note The default implementation is intentionally stateless.
     */
    virtual Status initialize_speculative_runtime(int, const device::Context&) { return {}; }
    /**
     * @brief Resets proposer-specific runtime state without affecting the target model.
     * @param context CUDA context used for any asynchronous reset operation.
     * @note The default implementation is intentionally stateless.
     */
    virtual Status reset_speculative_runtime(const device::Context&) { return {}; }
    /**
     * @brief Verifies that this proposer can consume context from a target model.
     * @param target Architecture-independent target dimensions.
     * @return Success or a structured model compatibility error.
     */
    virtual Status validate_target(const SpeculativeTargetMetadata& target) const = 0;
    /**
     * @brief Returns sorted zero-based target layers required as proposal context.
     * @return Non-owning view whose storage remains valid for the lifetime of the proposer.
     */
    [[nodiscard]] virtual std::span<const int> target_hidden_layers() const = 0;
    /**
     * @brief Returns the maximum proposal block length supported by the trained proposer.
     * @return Positive number of draft positions generated by one proposal call.
     */
    [[nodiscard]] virtual int block_size() const = 0;
    /**
     * @brief Produces a speculative token block and optional confidence scores.
     * @param input Anchor token, requested block length, target context, and CUDA context.
     * @return Device-resident proposal outputs owned by the caller.
     */
    [[nodiscard]] virtual Result<SpeculativeProposal> propose(const SpeculativeProposalInput& input) = 0;
};

/** @brief Type-erased snapshot base for model-specific speculative runtime state. */
struct SpeculativeRuntimeState
{
    /** @brief Enables destruction of implementation-defined snapshots through the base type. */
    virtual ~SpeculativeRuntimeState() = default;
};

/**
 * @brief Optional target capability for transactional speculative execution.
 *
 * Stateful targets snapshot the sequence slot before multi-token verification and restore
 * it before strict single-token replay. Stateless targets do not implement this interface.
 */
class SpeculativeTargetRuntime
{
public:
    /** @brief Enables destruction through the capability interface. */
    virtual ~SpeculativeTargetRuntime() = default;

    /**
     * @brief Captures all mutable target state associated with one sequence slot.
     * @param state_slot Runtime slot assigned by the scheduler.
     * @param context CUDA context used for asynchronous device copies.
     * @return Type-erased owned snapshot suitable for exactly one restore operation.
     */
    [[nodiscard]] virtual Result<std::unique_ptr<SpeculativeRuntimeState>> snapshot_speculative_runtime(
        int state_slot, const device::Context& context) = 0;
    /**
     * @brief Restores and consumes a previously captured sequence-state snapshot.
     * @param state Snapshot returned by this same model instance.
     * @param context CUDA context used for asynchronous device copies.
     */
    virtual Status restore_speculative_runtime(std::unique_ptr<SpeculativeRuntimeState> state,
                                               const device::Context&                   context) = 0;
};

}  // namespace firefly::model
