set(FIREFLY_CUDA_ARCHITECTURES "89" CACHE STRING "CUDA architectures used by Firefly kernels")

if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES OR CMAKE_CUDA_ARCHITECTURES STREQUAL "" OR CMAKE_CUDA_ARCHITECTURES STREQUAL "native")
    set(CMAKE_CUDA_ARCHITECTURES "${FIREFLY_CUDA_ARCHITECTURES}" CACHE STRING "CUDA architectures" FORCE)
endif()

foreach(ARCH IN LISTS CMAKE_CUDA_ARCHITECTURES)
    if(ARCH MATCHES "^[0-9]+" AND ARCH LESS 80)
        set(CMAKE_CUDA_ARCHITECTURES "${FIREFLY_CUDA_ARCHITECTURES}" CACHE STRING "CUDA architectures" FORCE)
        break()
    endif()
endforeach()

set(CMAKE_CUDA_STANDARD 20)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)

set(CMAKE_CUDA_EXTENSIONS OFF)
set(CMAKE_CUDA_SEPARABLE_COMPILATION OFF)

find_package(CUDAToolkit REQUIRED)
include_directories(${CUDAToolkit_INCLUDE_DIRS})

if(CMAKE_CUDA_COMPILER_ID STREQUAL "NVIDIA")
    add_compile_options(
        $<$<COMPILE_LANGUAGE:CUDA>:--expt-relaxed-constexpr>
        $<$<COMPILE_LANGUAGE:CUDA>:--use_fast_math>
    )
endif()
